/* ACDM - Administracao segura de clientes | Atlas Core 4.9.17 */
(function(w,d){"use strict";
var current=null,clients=[],certificates=[],selected=null;
function id(x){return d.getElementById(x)}
function norm(v){return String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}
function digits(v){return String(v||"").replace(/\D/g,"")}
function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]})}
function actor(){var n=d.querySelector("[data-auth-user-name]");return n?n.textContent.trim():"ATLAS"}
function certClientId(c){return String(c&&(c.clienteId||c.CLIENTE_ID||c.clientId||c.idCliente)||"")}
function parseDate(v){if(!v)return null;var t=String(v).trim(),m=t.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})/),x=m?new Date(+m[3],+m[2]-1,+m[1]):new Date(t);return isNaN(x.getTime())?null:x}
function hasActiveCertificate(client){var now=new Date();now.setHours(0,0,0,0);return certificates.some(function(c){if(certClientId(c)!==String(client.id))return false;if(c.active===false)return false;var status=norm(c.status||c.situacao);if(status.indexOf("cancel")>=0||status.indexOf("revog")>=0||status.indexOf("vencid")>=0)return false;var expiry=parseDate(c.vencimento||c.validade||c.dataValidade||c.DATA_VALIDADE);return !expiry||expiry>=now})}
function selectView(view){d.querySelectorAll("[data-acdm-view]").forEach(function(x){x.classList.toggle("active",x.dataset.acdmView===view)});d.querySelectorAll("[data-acdm-panel]").forEach(function(x){x.classList.toggle("active",x.dataset.acdmPanel===view)})}
function reset(){selected=null;id("acdm-search").value="";renderCandidates("");id("acdm-comparison").hidden=true;id("acdm-status").textContent="";["acdm-integrate-confirm","acdm-archive-confirm","acdm-delete-confirm"].forEach(function(x){if(id(x))id(x).checked=false});["acdm-integrate","acdm-archive","acdm-delete"].forEach(function(x){if(id(x))id(x).disabled=true});if(id("acdm-archive-reason"))id("acdm-archive-reason").value="";if(id("acdm-delete-reason"))id("acdm-delete-reason").value=""}
function open(view,candidateId){if(!current)return;id("acdm-modal").hidden=false;id("acdm-backdrop").hidden=false;id("acdm-subtitle").textContent=current.nome+" • "+(current.id||"");reset();selectView(view||"integrate");if(candidateId){var candidate=clients.find(function(c){return String(c.id)===String(candidateId)});if(candidate)compare(candidate)}}
function close(){id("acdm-modal").hidden=true;id("acdm-backdrop").hidden=true}
function renderCandidates(q){var nq=norm(q),nd=digits(q);var list=clients.filter(function(c){if(!current||String(c.id)===String(current.id))return false;var hay=norm([c.nome,c.empresa,c.email,c.telefone,c.whatsapp,c.cpfCnpj].join(" "));return !nq||hay.indexOf(nq)>=0||(nd&&digits(hay).indexOf(nd)>=0)}).slice(0,8);id("acdm-candidates").innerHTML=list.length?list.map(function(c){return'<button type="button" data-client="'+esc(c.id)+'"><span class="acdm-search-icon" aria-hidden="true">⌕</span><strong>'+esc(c.nome||"Cliente")+'</strong><small>'+esc(c.cpfCnpj||c.email||c.telefone||c.id)+'</small></button>'}).join(""):'<p>Nenhum cadastro localizado.</p>'}
function compare(c){if(!c)return;selected=c;id("acdm-comparison").hidden=false;id("acdm-comparison").innerHTML='<div><b>Cadastro atual</b><strong>'+esc(current.nome)+'</strong><small>'+esc(current.cpfCnpj||current.email||current.id)+'</small></div><span>⇄</span><div><b>Possível duplicidade</b><strong>'+esc(c.nome)+'</strong><small>'+esc(c.cpfCnpj||c.email||c.id)+'</small></div>';id("acdm-integrate").disabled=!id("acdm-integrate-confirm").checked}
async function integrate(){if(!current||!selected||!id("acdm-integrate-confirm").checked)return;var btn=id("acdm-integrate");btn.disabled=true;id("acdm-status").textContent="Unificando cadastros...";try{var note='[ACDM] Cadastro integrado ao cliente principal '+selected.id+' - '+selected.nome+'. Historico preservado.';await w.AtlasAPI.updateClient(current.id,{nome:current.nome,email:current.email,telefone:current.telefone,situacao:"INTEGRADO",responsavel:current.responsavel,observacoes:[current.observacoes,note].filter(Boolean).join("\n"),actor:actor()});await Promise.all([w.AtlasAPI.addTimeline({clienteId:current.id,tipoEvento:"CLIENTE_INTEGRADO",titulo:"Cadastro integrado",descricao:"Integrado ao cadastro principal "+selected.id+" - "+selected.nome,origem:"ACDM",actor:actor(),dados:{clientePrincipalId:selected.id}}),w.AtlasAPI.addTimeline({clienteId:selected.id,tipoEvento:"CLIENTE_RECEBEU_INTEGRACAO",titulo:"Cadastro relacionado integrado",descricao:"Cadastro "+current.id+" - "+current.nome+" foi integrado como registro historico.",origem:"ACDM",actor:actor(),dados:{clienteIntegradoId:current.id}}),w.AtlasAPI.audit("ACDM_CLIENT_MERGE",{sourceClientId:current.id,targetClientId:selected.id,username:actor()})]);id("acdm-status").textContent="Registros unificados com sucesso. O historico foi preservado.";setTimeout(function(){location.reload()},1200)}catch(e){id("acdm-status").textContent=e.message||"Nao foi possivel concluir a unificacao.";btn.disabled=false}}
async function archive(){if(!current||!id("acdm-archive-confirm").checked)return;var reason=id("acdm-archive-reason").value.trim()||"Arquivamento administrativo",btn=id("acdm-archive");btn.disabled=true;id("acdm-status").textContent="Arquivando cadastro...";try{var note='[ACDM] Cadastro arquivado. Motivo: '+reason;await w.AtlasAPI.updateClient(current.id,{nome:current.nome,email:current.email,telefone:current.telefone,situacao:"ARQUIVADO",responsavel:current.responsavel,observacoes:[current.observacoes,note].filter(Boolean).join("\n"),actor:actor()});await Promise.all([w.AtlasAPI.addTimeline({clienteId:current.id,tipoEvento:"CLIENTE_ARQUIVADO",titulo:"Cadastro arquivado",descricao:reason,origem:"ACDM",actor:actor()}),w.AtlasAPI.audit("ACDM_CLIENT_ARCHIVE",{clientId:current.id,reason:reason,username:actor()})]);id("acdm-status").textContent="Cadastro arquivado com sucesso.";setTimeout(function(){location.reload()},1200)}catch(e){id("acdm-status").textContent=e.message||"Nao foi possivel arquivar.";btn.disabled=false}}
async function removeClient(){if(!current||!id("acdm-delete-confirm").checked)return;var reason=id("acdm-delete-reason").value.trim(),btn=id("acdm-delete");if(!reason){id("acdm-status").textContent="Informe o motivo da exclusao.";return}if(hasActiveCertificate(current)){id("acdm-status").textContent="Exclusao bloqueada: este cliente possui certificado ativo. Arquive o cadastro ou regularize os certificados antes de excluir.";return}if(!w.confirm('Confirma a exclusao logica de "'+current.nome+'"? O historico sera preservado.'))return;btn.disabled=true;id("acdm-status").textContent="Excluindo cliente com seguranca...";try{var note='[ACDM] Cliente excluido logicamente. Motivo: '+reason;await w.AtlasAPI.updateClient(current.id,{nome:current.nome,email:current.email,telefone:current.telefone,situacao:"EXCLUIDO",status:"EXCLUIDO",responsavel:current.responsavel,observacoes:[current.observacoes,note].filter(Boolean).join("\n"),actor:actor()});await Promise.all([w.AtlasAPI.addTimeline({clienteId:current.id,tipoEvento:"CLIENTE_EXCLUIDO",titulo:"Cliente excluido logicamente",descricao:reason,origem:"ACDM",actor:actor()}),w.AtlasAPI.audit("ACDM_CLIENT_SOFT_DELETE",{clientId:current.id,reason:reason,username:actor()})]);id("acdm-status").textContent="Cliente excluido logicamente. Historico e auditoria preservados.";setTimeout(function(){location.reload()},1300)}catch(e){id("acdm-status").textContent=e.message||"Nao foi possivel excluir o cliente.";btn.disabled=false}}
async function init(){if(!id("crm-action-admin"))return;try{var data=await Promise.all([w.AtlasAPI.listClients(),w.AtlasAPI.listCertificates()]);clients=Array.isArray(data[0])?data[0]:[];certificates=Array.isArray(data[1])?data[1]:[]}catch(e){clients=[];certificates=[]}id("crm-action-admin").addEventListener("click",function(){open("integrate")});id("acdm-close").addEventListener("click",close);id("acdm-backdrop").addEventListener("click",close);id("acdm-search").addEventListener("input",function(){renderCandidates(this.value)});id("acdm-candidates").addEventListener("click",function(e){var b=e.target.closest("button[data-client]");if(!b)return;compare(clients.find(function(c){return String(c.id)===String(b.dataset.client)}))});d.querySelectorAll("[data-acdm-view]").forEach(function(b){b.addEventListener("click",function(){selectView(b.dataset.acdmView)})});id("acdm-integrate-confirm").addEventListener("change",function(){id("acdm-integrate").disabled=!(this.checked&&selected)});id("acdm-archive-confirm").addEventListener("change",function(){id("acdm-archive").disabled=!this.checked});id("acdm-delete-confirm").addEventListener("change",function(){id("acdm-delete").disabled=!this.checked});id("acdm-integrate").addEventListener("click",integrate);id("acdm-archive").addEventListener("click",archive);id("acdm-delete").addEventListener("click",removeClient);d.addEventListener("atlas:client-opened",function(e){current=e.detail.client});d.addEventListener("atlas:acdm-open",function(e){var detail=e.detail||{};if(detail.clientId){current=clients.find(function(c){return String(c.id)===String(detail.clientId)})||current}open(detail.view||"integrate",detail.candidateId)});d.addEventListener("keydown",function(e){if(e.key==="Escape"&&!id("acdm-modal").hidden)close()})}
if(d.readyState==="loading")d.addEventListener("DOMContentLoaded",init);else init()
})(window,document);