(function(){
  "use strict";
  var appointments=[],clients=[],view="week",reference=new Date();
  function id(x){return document.getElementById(x)} function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
  function local(v){var d=new Date(v);if(isNaN(d))return"";d=new Date(d.getTime()-d.getTimezoneOffset()*60000);return d.toISOString().slice(0,16)}
  function limits(){var a=new Date(reference),b=new Date(reference);a.setHours(0,0,0,0);b.setHours(23,59,59,999);if(view==="week"){var n=(a.getDay()+6)%7;a.setDate(a.getDate()-n);b=new Date(a);b.setDate(b.getDate()+6);b.setHours(23,59,59,999)}if(view==="month"){a=new Date(a.getFullYear(),a.getMonth(),1);b=new Date(a.getFullYear(),a.getMonth()+1,0,23,59,59,999)}return[a,b]}
  function render(){var today=new Date().toDateString();id("agenda-today").textContent=appointments.filter(function(x){return new Date(x.inicio).toDateString()===today}).length;id("agenda-requested").textContent=appointments.filter(function(x){return x.situacao==="SOLICITADO"}).length;id("agenda-confirmed").textContent=appointments.filter(function(x){return x.situacao==="CONFIRMADO"}).length;id("agenda-completed").textContent=appointments.filter(function(x){return x.situacao==="CONCLUIDO"}).length;id("agenda-list").innerHTML=appointments.length?appointments.map(function(x){var d=new Date(x.inicio);return '<article class="agenda-item"><time>'+d.toLocaleDateString("pt-BR")+"<br>"+d.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})+'</time><div><span class="agenda-status">'+esc(x.situacao.replace(/_/g," "))+'</span><h2>'+esc(x.titulo)+'</h2><p>'+esc(x.clienteNome)+" • "+esc(x.tipo)+" • "+esc(x.responsavel||"A definir")+'</p></div><button data-edit="'+esc(x.id)+'">Editar</button></article>'}).join(""):'<div class="agenda-empty">Nenhum atendimento neste período.</div>'}
  function load(){var l=limits();return Promise.all([window.AtlasAPI.request("agenda.list",{inicio:l[0].toISOString(),fim:l[1].toISOString()}),clients.length?Promise.resolve(clients):window.AtlasAPI.listClients()]).then(function(out){appointments=out[0]||[];clients=out[1]||[];id("agenda-client").innerHTML='<option value="">Selecione...</option>'+clients.map(function(c){return '<option value="'+esc(c.id)+'">'+esc(c.name||c.nome||c.company||c.id)+'</option>'}).join("");render()}).catch(function(e){id("agenda-list").innerHTML='<div class="agenda-empty">'+esc(e.message)+'</div>'})}
  function open(item){id("agenda-form").reset();id("agenda-id").value=item?item.id:"";id("agenda-form-title").textContent=item?"Editar agendamento":"Novo agendamento";if(item){id("agenda-client").value=item.clienteId;id("agenda-title").value=item.titulo;id("agenda-type").value=item.tipo;id("agenda-status").value=item.situacao;id("agenda-start").value=local(item.inicio);id("agenda-end").value=local(item.fim);id("agenda-owner").value=item.responsavel;id("agenda-location").value=item.localLink;id("agenda-notes").value=item.observacoes}else{var start=new Date();start.setMinutes(Math.ceil(start.getMinutes()/30)*30,0,0);var end=new Date(start.getTime()+30*60000);id("agenda-start").value=local(start);id("agenda-end").value=local(end);id("agenda-title").value="Atendimento de certificado digital"}id("agenda-modal").hidden=false}
  function close(){id("agenda-modal").hidden=true}
  id("agenda-new").onclick=function(){open(null)};id("agenda-close").onclick=close;id("agenda-cancel").onclick=close;id("agenda-refresh").onclick=load;id("agenda-reference").value=new Date().toISOString().slice(0,10);id("agenda-reference").onchange=function(){reference=new Date(this.value+"T12:00:00");load()};document.querySelectorAll("[data-view]").forEach(function(b){b.onclick=function(){document.querySelectorAll("[data-view]").forEach(function(x){x.classList.remove("active")});b.classList.add("active");view=b.dataset.view;load()}});
  id("agenda-list").onclick=function(e){var b=e.target.closest("[data-edit]");if(b)open(appointments.find(function(x){return x.id===b.dataset.edit}))};
  id("agenda-form").onsubmit=function(e){e.preventDefault();var key=id("agenda-id").value,p={id:key,clienteId:id("agenda-client").value,titulo:id("agenda-title").value,tipo:id("agenda-type").value,situacao:id("agenda-status").value,inicio:id("agenda-start").value,fim:id("agenda-end").value,responsavel:id("agenda-owner").value,localLink:id("agenda-location").value,observacoes:id("agenda-notes").value},button=e.currentTarget.querySelector('button[type="submit"]');button.disabled=true;window.AtlasAPI.request(key?"agenda.update":"agenda.create",p).then(function(){close();return load()}).catch(function(err){id("agenda-feedback").hidden=false;id("agenda-feedback").textContent=err.message}).finally(function(){button.disabled=false})};
  load();
})();
