/* Atlas ACMS Interface v1.0 - Central de Clientes e Ficha 360 4.9.2 | Marcos Henrique Pedroza */
(function(window,document){
  "use strict";
  var state={clients:[],certificates:[],timeline:[],sectors:{setores:[],subsetores:[]},rows:[],filtered:[],filter:"all",query:"",page:1,pageSize:25,sort:"name",direction:1,drawer:null,lastFocus:null};
  var el={};
  function byId(id){return document.getElementById(id)}
  function text(id,value){var node=byId(id);if(node)node.textContent=String(value==null?"":value)}
  function digits(value){return String(value||"").replace(/\D/g,"")}
  function normalize(value){return String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim()}
  function escapeHtml(value){return String(value==null?"":value).replace(/[&<>'"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]})}
  function parseDate(value){if(!value)return null;if(Object.prototype.toString.call(value)==="[object Date]")return value;var s=String(value).trim();var br=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})/);var d=br?new Date(+br[3],+br[2]-1,+br[1]):new Date(s);return isNaN(d.getTime())?null:d}
  function dayDiff(date){if(!date)return null;var now=new Date();now.setHours(0,0,0,0);var copy=new Date(date);copy.setHours(0,0,0,0);return Math.ceil((copy-now)/86400000)}
  function formatDate(date,withTime){if(!date)return"—";return new Intl.DateTimeFormat("pt-BR",withTime?{dateStyle:"short",timeStyle:"short"}:{}).format(date)}
  function formatDoc(value){var d=digits(value);if(d.length===11)return d.replace(/(\d{3})(\d{3})(\d{3})(\d{2})/,"$1.$2.$3-$4");if(d.length===14)return d.replace(/(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})/,"$1.$2.$3/$4-$5");return value||"—"}
  function formatPhone(value){var d=digits(value);if(d.length===11)return d.replace(/(\d{2})(\d{5})(\d{4})/,"($1) $2-$3");if(d.length===10)return d.replace(/(\d{2})(\d{4})(\d{4})/,"($1) $2-$3");return value||"—"}
  function initials(name){return normalize(name).split(/\s+/).filter(Boolean).slice(0,2).map(function(x){return x.charAt(0).toUpperCase()}).join("")||"CL"}
  function certStatus(cert){return normalize(cert.statusCertificado||"")}
  function isRenewal(row){return /renov/.test(normalize(row.client.situacao+" "+row.client.observacoes+" "+(row.certificate&&row.certificate.statusCertificado||"")))}
  function sectorName(id,type){var list=state.sectors[type]||[];var found=list.find(function(x){return String(x.ID||x.id)===String(id)});return found?String(found.NOME||found.nome||""):""}
  function chooseCertificate(clientId){var list=state.certificates.filter(function(c){return String(c.clienteId)===String(clientId)&&c.active!==false});if(!list.length)return null;list.sort(function(a,b){var da=parseDate(a.vencimento),db=parseDate(b.vencimento);if(!da)return 1;if(!db)return-1;return da-db});var future=list.find(function(c){var d=dayDiff(parseDate(c.vencimento));return d!==null&&d>=0});return future||list[list.length-1]}
  function buildRows(){state.rows=state.clients.map(function(client){var certificate=chooseCertificate(client.id),expiry=parseDate(certificate&&certificate.vencimento),days=dayDiff(expiry),events=state.timeline.filter(function(t){return String(t.CLIENTE_ID||t.clienteId)===String(client.id)}),sector=sectorName(client.setorId,"setores"),subsector=sectorName(client.subsetorId,"subsetores"),haystack=normalize([client.id,client.nome,client.empresa,client.cpfCnpj,client.telefone,client.whatsapp,client.email,client.emailSecundario,client.cidade,client.uf,client.situacao,client.responsavel,client.observacoes,sector,subsector,certificate&&certificate.id,certificate&&certificate.tipo,certificate&&certificate.numeroSerie,certificate&&certificate.statusCertificado,events.map(function(e){return[e.TITULO,e.DESCRICAO,e.TIPO_EVENTO].join(" ")}).join(" ")].join(" "));return{client:client,certificate:certificate,expiry:expiry,days:days,events:events,sector:sector,subsector:subsector,haystack:haystack}})}
  function category(row){if(!row.client.active||normalize(row.client.situacao)==="inativo")return"inactive";if(row.days!==null&&row.days<0)return"expired";if(isRenewal(row))return"renewal";if(row.days!==null&&row.days<=30)return"30";if(row.days!==null&&row.days<=60)return"60";if(row.days!==null&&row.days<=90)return"90";return"active"}
  function matchesFilter(row){var c=category(row);switch(state.filter){case"active":return c!=="inactive";case"inactive":return c==="inactive";case"30":return row.days!==null&&row.days>=0&&row.days<=30;case"60":return row.days!==null&&row.days>=0&&row.days<=60;case"90":return row.days!==null&&row.days>=0&&row.days<=90;case"renewal":return isRenewal(row);default:return true}}
  function priority(row){var p=normalize(row.client.prioridade);if(p.indexOf("alta")>=0||p.indexOf("urg")>=0||row.days!==null&&row.days<=30)return 3;if(p.indexOf("media")>=0||row.days!==null&&row.days<=60)return 2;return 1}
  function sortValue(row,key){switch(key){case"priority":return priority(row);case"company":return normalize(row.client.empresa);case"certificate":return normalize(row.certificate&&row.certificate.tipo);case"expiry":return row.expiry?row.expiry.getTime():Infinity;case"days":return row.days===null?Infinity:row.days;default:return normalize(row.client.nome)}}
  function apply(){var q=normalize(state.query);state.filtered=state.rows.filter(function(row){return matchesFilter(row)&&(!q||row.haystack.indexOf(q)>=0||digits(row.haystack).indexOf(digits(q))>=0&&digits(q).length>=4)});state.filtered.sort(function(a,b){var x=sortValue(a,state.sort),y=sortValue(b,state.sort);return(typeof x==="number"?x-y:String(x).localeCompare(String(y),"pt-BR"))*state.direction});var pages=Math.max(1,Math.ceil(state.filtered.length/state.pageSize));if(state.page>pages)state.page=pages;render()}
  function statusInfo(row){var c=category(row);if(c==="inactive")return{label:"Inativo",css:"inactive"};if(c==="expired")return{label:"Vencido",css:"danger"};if(c==="renewal")return{label:"Renovação",css:"warning"};if(row.days!==null&&row.days<=30)return{label:"Vence em breve",css:"warning"};return{label:"Ativo",css:"ok"}}
  function priorityInfo(row){var p=priority(row);return p===3?{label:"Alta",css:"high"}:p===2?{label:"Média",css:"medium"}:{label:"Normal",css:"normal"}}
  function rowHtml(row){var c=row.client,cert=row.certificate,status=statusInfo(row),prio=priorityInfo(row),dayClass=row.days!==null&&row.days<0?"danger":row.days!==null&&row.days<=30?"warning":"";return'<tr tabindex="0" role="button" aria-label="Abrir Ficha 360º de '+escapeHtml(c.nome||"cliente")+'" data-client-id="'+escapeHtml(c.id)+'"><td><span class="crm-priority '+prio.css+'"><i></i>'+prio.label+'</span></td><td><div class="crm-client"><span class="crm-avatar">'+escapeHtml(initials(c.nome))+'</span><span><strong>'+escapeHtml(c.nome||"Sem nome")+'</strong><small>'+escapeHtml(c.email||c.telefone||"Sem contato principal")+'</small></span></div></td><td class="crm-company">'+escapeHtml(c.empresa||"—")+'</td><td class="crm-doc">'+escapeHtml(formatDoc(c.cpfCnpj))+'</td><td>'+escapeHtml([c.cidade,c.uf].filter(Boolean).join("/")||"—")+'</td><td>'+(cert?'<strong>'+escapeHtml(cert.tipo||"Certificado")+'</strong><br><small>'+escapeHtml(cert.numeroSerie||cert.id||"")+'</small>':'<span class="crm-muted">Sem certificado</span>')+'</td><td>'+formatDate(row.expiry)+'</td><td class="crm-days '+dayClass+'">'+(row.days===null?"—":row.days<0?Math.abs(row.days)+" vencido":row.days)+'</td><td><span class="crm-status '+status.css+'">'+status.label+'</span></td><td>'+escapeHtml(c.responsavel||"—")+'</td></tr>'}
  function render(){var start=(state.page-1)*state.pageSize,end=Math.min(start+state.pageSize,state.filtered.length),slice=state.filtered.slice(start,end);el.body.innerHTML=slice.map(rowHtml).join("");el.table.hidden=!slice.length;el.empty.hidden=!!slice.length;el.pagination.hidden=!state.filtered.length;text("crm-result-count",state.filtered.length+" registro"+(state.filtered.length===1?"":"s"));text("crm-range",state.filtered.length?(start+1)+"–"+end+" de "+state.filtered.length:"0 de 0");renderPages();updateCounts()}
  function renderPages(){var total=Math.max(1,Math.ceil(state.filtered.length/state.pageSize));el.prev.disabled=state.page<=1;el.next.disabled=state.page>=total;var from=Math.max(1,state.page-2),to=Math.min(total,from+4);from=Math.max(1,to-4);var html="";for(var i=from;i<=to;i++)html+='<button type="button" data-page="'+i+'" class="'+(i===state.page?"active":"")+'">'+i+'</button>';el.pages.innerHTML=html}
  function updateCounts(){var counts={all:state.rows.length,active:0,inactive:0,"30":0,"60":0,"90":0,renewal:0};state.rows.forEach(function(r){if(category(r)==="inactive")counts.inactive++;else counts.active++;if(r.days!==null&&r.days>=0&&r.days<=30)counts["30"]++;if(r.days!==null&&r.days>=0&&r.days<=60)counts["60"]++;if(r.days!==null&&r.days>=0&&r.days<=90)counts["90"]++;if(isRenewal(r))counts.renewal++});Object.keys(counts).forEach(function(k){text("count-"+k,counts[k])})}
  function updateKpis(){text("crm-kpi-total",state.clients.length);text("crm-kpi-active",state.rows.filter(function(r){return category(r)!=="inactive"}).length);text("crm-kpi-certificates",state.certificates.filter(function(c){return c.active!==false&&certStatus(c)!=="vencido"}).length);text("crm-kpi-30",state.rows.filter(function(r){return r.days!==null&&r.days>=0&&r.days<=30}).length);text("crm-kpi-renewals",state.rows.filter(isRenewal).length)}
  function loading(value){el.loading.hidden=!value;if(value){el.table.hidden=true;el.empty.hidden=true;el.error.hidden=true;el.pagination.hidden=true}}
  function setSync(mode,title,detail){el.sync.className="crm-sync "+mode;el.sync.querySelector("strong").textContent=title;text("crm-sync-time",detail)}
  function field(label,value,wide){return'<div class="crm-data-field'+(wide?' wide':'')+'"><small>'+escapeHtml(label)+'</small><strong>'+escapeHtml(value||"—")+'</strong></div>'}
  function emptyState(icon,title,description){return'<div class="crm-tab-empty"><b>'+icon+'</b><h3>'+escapeHtml(title)+'</h3><p>'+escapeHtml(description)+'</p></div>'}
  function timelineDate(item){return parseDate(item.DATA_HORA||item.CRIADO_EM||item.dataHora)}
  function timelineHtml(items){if(!items.length)return emptyState("◷","Nenhum evento registrado","A API não retornou eventos de timeline para este cliente.");return'<div class="crm-timeline-list">'+items.map(function(item){var type=String(item.TIPO_EVENTO||"ATIVIDADE").replace(/_/g," ");return'<article><span class="crm-timeline-icon">'+(type.indexOf("RENOV")>=0?'↻':type.indexOf("COMUNIC")>=0?'✉':type.indexOf("EMISS")>=0?'✓':'•')+'</span><div><small>'+escapeHtml(type)+' • '+escapeHtml(formatDate(timelineDate(item),true))+'</small><h3>'+escapeHtml(item.TITULO||"Atividade")+'</h3><p>'+escapeHtml(item.DESCRICAO||"Sem descrição adicional.")+'</p><em>'+escapeHtml(item.USUARIO_LOGIN||item.CRIADO_POR||item.ORIGEM||"ATLAS")+'</em></div></article>'}).join("")+'</div>'}
  function certificateHtml(items){if(!items.length)return emptyState("▤","Nenhum certificado vinculado","Não existem certificados associados ao cadastro na base oficial.");items=items.slice().sort(function(a,b){return(parseDate(b.vencimento)||0)-(parseDate(a.vencimento)||0)});return'<div class="crm-certificate-list">'+items.map(function(cert){var expiry=parseDate(cert.vencimento),days=dayDiff(expiry),css=days===null?"inactive":days<0?"danger":days<=30?"warning":"ok",label=days===null?"Sem validade":days<0?"Vencido há "+Math.abs(days)+" dias":days+" dias restantes";return'<article><div><span class="crm-status '+css+'">'+escapeHtml(cert.statusCertificado||label)+'</span><h3>'+escapeHtml(cert.tipo||"Certificado digital")+'</h3><p>'+escapeHtml(cert.autoridadeCertificadora||"Autoridade certificadora não informada")+'</p></div><dl><div><dt>Emissão</dt><dd>'+formatDate(parseDate(cert.emissao))+'</dd></div><div><dt>Vencimento</dt><dd>'+formatDate(expiry)+'</dd></div><div><dt>Série</dt><dd>'+escapeHtml(cert.numeroSerie||cert.id||"—")+'</dd></div><div><dt>Situação</dt><dd class="crm-cert-days '+css+'">'+escapeHtml(label)+'</dd></div></dl></article>'}).join("")+'</div>'}
  function communicationHtml(items){if(!items.length)return emptyState("✉","Nenhuma comunicação registrada","A Atlas API não retornou e-mails, WhatsApp ou campanhas vinculadas a este cliente.");return'<div class="crm-communication-list">'+items.map(function(item){var when=parseDate(item.ENVIADO_EM||item.AGENDADO_PARA||item.CRIADO_EM),channel=item.CANAL||"COMUNICAÇÃO";return'<article><span>'+escapeHtml(channel.charAt(0))+'</span><div><small>'+escapeHtml(channel)+' • '+escapeHtml(formatDate(when,true))+'</small><h3>'+escapeHtml(item.ASSUNTO||"Comunicação")+'</h3><p>'+escapeHtml(item.DESTINO||"Destino não informado")+'</p></div><em>'+escapeHtml(item.STATUS_ENVIO||item.STATUS||"Registrada")+'</em></article>'}).join("")+'</div>'}
  function renderDrawer(data){var c=data.cliente||{},row=state.rows.find(function(r){return String(r.client.id)===String(c.id)})||{client:c,days:null},status=statusInfo(row),address=[c.endereco,c.numero,c.complemento,c.bairro].filter(Boolean).join(", "),sector=sectorName(c.setorId,"setores"),subsector=sectorName(c.subsetorId,"subsetores"),certs=Array.isArray(data.certificados)?data.certificados:[],timeline=Array.isArray(data.timeline)?data.timeline:[],comms=Array.isArray(data.comunicacoes)?data.comunicacoes:[],tags=Array.isArray(data.tags)?data.tags:[];
    text("crm-drawer-avatar",initials(c.nome));text("crm-drawer-title",c.nome||"Cliente");text("crm-drawer-company",c.empresa||formatDoc(c.cpfCnpj));text("crm-drawer-owner","Responsável: "+(c.responsavel||"Não informado"));byId("crm-drawer-status").className="crm-status "+status.css;text("crm-drawer-status",status.label);text("crm-tab-cert-count",certs.length);text("crm-tab-timeline-count",timeline.length);text("crm-tab-comm-count",comms.length);
    var whatsapp=digits(c.whatsapp||c.telefone),mail=c.email||c.emailSecundario;var wa=byId("crm-action-whatsapp"),em=byId("crm-action-email");wa.href=whatsapp?"https://wa.me/55"+whatsapp:"#";wa.classList.toggle("disabled",!whatsapp);em.href=mail?"mailto:"+mail:"#";em.classList.toggle("disabled",!mail);byId("crm-action-copy").dataset.value=c.cpfCnpj||"";
    byId("crm-panel-geral").innerHTML='<div class="crm-data-grid">'+field("Nome",c.nome,true)+field("Empresa",c.empresa,true)+field("CPF/CNPJ",formatDoc(c.cpfCnpj))+field("Situação",c.situacao||status.label)+field("Telefone",formatPhone(c.telefone))+field("WhatsApp",formatPhone(c.whatsapp))+field("E-mail",c.email,true)+field("E-mail secundário",c.emailSecundario,true)+field("Endereço",address||"—",true)+field("Cidade / UF",[c.cidade,c.uf].filter(Boolean).join(" / "))+field("CEP",c.cep)+field("Setor",sector)+field("Subsetor",subsector)+field("Horário preferencial",c.horarioPreferencial)+field("Prioridade",c.prioridade)+field("Tags",tags.map(function(t){return t.TAG_ID||t.NOME||t.nome}).filter(Boolean).join(", ")||"—",true)+'</div>';
    byId("crm-panel-certificados").innerHTML=certificateHtml(certs);byId("crm-panel-timeline").innerHTML=timelineHtml(timeline);byId("crm-panel-comunicacao").innerHTML=communicationHtml(comms);
    byId("crm-panel-agenda").innerHTML=emptyState("□","Agenda ainda sem dados expostos","A API homologada não possui endpoint de agenda por cliente nesta versão. Nenhuma planilha foi acessada diretamente.");
    byId("crm-panel-observacoes").innerHTML=c.observacoes?'<article class="crm-note"><small>Observação interna</small><p>'+escapeHtml(c.observacoes)+'</p></article>':emptyState("✎","Sem observações","Nenhuma observação interna foi retornada para este cliente.");
    var auditItems=timeline.filter(function(i){return /ALTER|CADAST|ATUALIZ|IMPORT/.test(String(i.TIPO_EVENTO||"").toUpperCase())});byId("crm-panel-auditoria").innerHTML=auditItems.length?timelineHtml(auditItems):emptyState("◎","Sem eventos de auditoria na ficha","A API atual não expõe a tabela de auditoria por cliente; foram considerados apenas eventos compatíveis da timeline.");
  }
  function selectTab(name){document.querySelectorAll("#crm-drawer-tabs button").forEach(function(b){b.classList.toggle("active",b.dataset.tab===name)});document.querySelectorAll(".crm-tab-panel").forEach(function(p){p.classList.toggle("active",p.dataset.panel===name)})}
  async function openDrawer(clientId){state.lastFocus=document.activeElement;el.drawer.classList.add("open");el.backdrop.hidden=false;el.drawer.setAttribute("aria-hidden","false");document.body.classList.add("crm-drawer-open");el.drawerLoading.hidden=false;el.drawerContent.classList.add("is-loading");selectTab("geral");try{var data=await window.AtlasAPI.getClient(clientId);state.drawer=data;renderDrawer(data);try{window.AtlasAPI.audit("CRM_CLIENT_360_VIEW",{clientId:clientId});}catch(ignore){} }catch(error){byId("crm-panel-geral").innerHTML=emptyState("!","Não foi possível abrir a ficha",error.message||"Falha inesperada na Atlas API.");}finally{el.drawerLoading.hidden=true;el.drawerContent.classList.remove("is-loading");byId("crm-drawer-close").focus()}}
  function closeDrawer(){el.drawer.classList.remove("open");el.backdrop.hidden=true;el.drawer.setAttribute("aria-hidden","true");document.body.classList.remove("crm-drawer-open");state.drawer=null;if(state.lastFocus&&state.lastFocus.focus)state.lastFocus.focus()}
  async function load(){loading(true);setSync("","Conectando à Atlas API","Aguarde...");try{if(!window.AtlasAPI||!window.AtlasAPI.isConfigured())throw new Error("Atlas API não configurada.");var result=await Promise.all([window.AtlasAPI.listClients(),window.AtlasAPI.listCertificates(),window.AtlasAPI.listTimeline({limit:5000}),window.AtlasAPI.listSectors()]);state.clients=Array.isArray(result[0])?result[0]:[];state.certificates=Array.isArray(result[1])?result[1]:[];state.timeline=Array.isArray(result[2])?result[2]:[];state.sectors=result[3]||{setores:[],subsetores:[]};buildRows();updateKpis();state.page=1;apply();loading(false);setSync("online","Dados sincronizados",new Intl.DateTimeFormat("pt-BR",{hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(new Date()));try{window.AtlasAPI.audit("CRM_CLIENTS_VIEW",{clients:state.clients.length,certificates:state.certificates.length})}catch(ignore){}}catch(error){loading(false);el.error.hidden=false;setSync("error","Falha de sincronização","Atlas API indisponível");text("crm-error-message",error.message||"Falha inesperada ao carregar os dados.")}}
  function debounce(fn,wait){var timer;return function(){var args=arguments;clearTimeout(timer);timer=setTimeout(function(){fn.apply(null,args)},wait)}}
  function bind(){el.search.addEventListener("input",debounce(function(){state.query=el.search.value;state.page=1;el.clear.hidden=!state.query;apply()},180));el.clear.addEventListener("click",function(){el.search.value="";state.query="";state.page=1;el.clear.hidden=true;el.search.focus();apply()});byId("crm-filters").addEventListener("click",function(e){var b=e.target.closest("button[data-filter]");if(!b)return;state.filter=b.dataset.filter;state.page=1;document.querySelectorAll("#crm-filters button").forEach(function(x){x.classList.toggle("active",x===b)});apply()});byId("crm-page-size").addEventListener("change",function(e){state.pageSize=Number(e.target.value)||25;state.page=1;apply()});el.prev.addEventListener("click",function(){if(state.page>1){state.page--;render()}});el.next.addEventListener("click",function(){var total=Math.ceil(state.filtered.length/state.pageSize);if(state.page<total){state.page++;render()}});el.pages.addEventListener("click",function(e){var b=e.target.closest("button[data-page]");if(b){state.page=Number(b.dataset.page);render()}});document.querySelector(".crm-table thead").addEventListener("click",function(e){var b=e.target.closest("button[data-sort]");if(!b)return;if(state.sort===b.dataset.sort)state.direction*=-1;else{state.sort=b.dataset.sort;state.direction=1}apply()});el.body.addEventListener("click",function(e){var row=e.target.closest("tr[data-client-id]");if(row)openDrawer(row.dataset.clientId)});el.body.addEventListener("keydown",function(e){var row=e.target.closest("tr[data-client-id]");if(row&&(e.key==="Enter"||e.key===" ")){e.preventDefault();openDrawer(row.dataset.clientId)}});byId("crm-refresh").addEventListener("click",load);byId("crm-error-retry").addEventListener("click",load);byId("crm-drawer-close").addEventListener("click",closeDrawer);el.backdrop.addEventListener("click",closeDrawer);byId("crm-drawer-tabs").addEventListener("click",function(e){var b=e.target.closest("button[data-tab]");if(b)selectTab(b.dataset.tab)});byId("crm-action-copy").addEventListener("click",function(){var value=this.dataset.value;if(!value)return;navigator.clipboard.writeText(value).then(function(){text("crm-action-copy","Documento copiado");setTimeout(function(){text("crm-action-copy","Copiar documento")},1600)})});document.addEventListener("keydown",function(e){if(e.key==="Escape"&&el.drawer.classList.contains("open"))closeDrawer();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();el.search.focus()}})}
  function init(){el={search:byId("crm-search"),clear:byId("crm-search-clear"),body:byId("crm-table-body"),table:byId("crm-table"),empty:byId("crm-empty"),error:byId("crm-error"),loading:byId("crm-loading"),pagination:byId("crm-pagination"),prev:byId("crm-prev"),next:byId("crm-next"),pages:byId("crm-pages"),sync:byId("crm-sync"),drawer:byId("crm-drawer"),backdrop:byId("crm-drawer-backdrop"),drawerLoading:byId("crm-drawer-loading"),drawerContent:byId("crm-drawer-content")};bind();load()}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})(window,document);
