/* Atlas Cockpit Enterprise 5.0.5.2 | Shared Cache e Navegacao Instantanea */
(function(window,document){"use strict";
var CACHE="cockpit";
function el(id){return document.getElementById(id)}function set(id,v){var n=el(id);if(n)n.textContent=String(v)}
function esc(v){return String(v==null?"":v).replace(/[&<>\"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]})}
function date(v){if(!v)return null;if(v instanceof Date)return v;var r=String(v).trim(),m=r.match(/^(\d{2})\/(\d{2})\/(\d{4})(?:\s+(\d{2}):(\d{2}))?/);if(m)return new Date(+m[3],+m[2]-1,+m[1],+(m[4]||0),+(m[5]||0));var d=new Date(r);return isNaN(d)?null:d}
function start(d){d=new Date(d);d.setHours(0,0,0,0);return d}function daysTo(v){var d=date(v);return d?Math.round((start(d)-start(new Date()))/86400000):null}
function format(v){var d=date(v);return d?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(d):"Agora"}
function find(o,names,def){for(var i=0;i<names.length;i++){if(o&&o[names[i]]!==undefined&&o[names[i]]!=="")return o[names[i]]}return def}
function activateCards(){document.querySelectorAll('[data-dashboard-target]').forEach(function(n){function go(){var t=n.getAttribute('data-dashboard-target');if(t)location.href=t}n.onclick=go;n.onkeydown=function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}}})}
function renderCertificates(list){var counts={expired:0,d7:0,d30:0,active:0},ranked=[];(list||[]).forEach(function(c){if(c.active===false)return;var d=daysTo(find(c,['vencimento','VALIDADE','DATA_VENCIMENTO','validade']));if(d===null)return;if(d<0)counts.expired++;else{counts.active++;if(d<=7)counts.d7++;if(d<=30)counts.d30++}ranked.push({c:c,d:d})});set('atlas-kpi-expired',counts.expired);set('atlas-kpi-due-7',counts.d7);set('atlas-kpi-due-30',counts.d30);set('atlas-kpi-certificates',counts.active);ranked.sort(function(a,b){return a.d-b.d});var box=el('atlas-ai-list');if(!box)return;var items=ranked.filter(function(x){return x.d<=30}).slice(0,4);box.innerHTML=items.length?items.map(function(x){var name=find(x.c,['clienteNome','NOME_CLIENTE','nome','razaoSocial'],'Cliente'),msg=x.d<0?'Certificado vencido há '+Math.abs(x.d)+' dia(s)':x.d===0?'Certificado vence hoje':'Certificado vence em '+x.d+' dia(s)';return '<div class="cockpit-ai-item '+(x.d<=0?'danger':'')+'"><i></i><span><strong>'+esc(name)+'</strong><small>'+esc(msg)+' • ação recomendada: contatar cliente</small></span><a href="comunicacao.html">Enviar</a></div>'}).join(''):'<div class="cockpit-empty"><p>Nenhuma prioridade crítica.</p><small>A operação está em dia.</small></div>'}
function renderTimeline(list){var box=el('atlas-activity-list'),today=start(new Date()),todayCount=0;if(!box)return;var rows=(list||[]).slice(0,8);rows.forEach(function(x){var d=date(find(x,['DATA_HORA','createdAt','timestamp']));if(d&&start(d).getTime()===today.getTime())todayCount++});set('atlas-kpi-activity-today',todayCount+' hoje');box.innerHTML=rows.length?rows.map(function(x){var a=find(x,['ACAO','TIPO_EVENTO','type','action'],'ATIVIDADE'),u=find(x,['USUARIO_LOGIN','username','user','TITULO'],'Sistema Atlas'),w=find(x,['DATA_HORA','createdAt','timestamp'],Date.now());return '<div class="cockpit-activity"><i></i><span><strong>'+esc(String(a).replace(/_/g,' '))+'</strong><small>'+esc(u)+'</small></span><time>'+format(w)+'</time></div>'}).join(''):'<div class="cockpit-empty"><p>Nenhuma atividade recente.</p></div>'}
function renderAgenda(list){var box=el('atlas-agenda-list');if(!box)return;var rows=(list||[]).filter(function(x){var d=date(find(x,['inicio','INICIO']));return d&&d>=new Date(Date.now()-3600000)}).slice(0,5);box.className=rows.length?'cockpit-agenda-list':'cockpit-empty';box.innerHTML=rows.length?rows.map(function(x){return '<div class="cockpit-activity"><i></i><span><strong>'+esc(find(x,['titulo','TITULO'],'Atendimento'))+'</strong><small>'+esc(find(x,['clienteNome','NOME_CLIENTE'],'Cliente'))+' • '+esc(String(find(x,['situacao','SITUACAO'],'SOLICITADO')).replace(/_/g,' '))+'</small></span><time>'+format(find(x,['inicio','INICIO']))+'</time></div>'}).join(''):'<b>□</b><p>Nenhum atendimento próximo.</p><small>Solicitações do Portal aparecem aqui automaticamente.</small>'}
function renderComms(list,automation){var today=start(new Date()),sent=0,pending=0,errors=0,invites=0;(list||[]).forEach(function(x){var d=date(find(x,['DATA_HORA','ENVIADO_EM','createdAt','timestamp'])),st=String(find(x,['STATUS_ENVIO','STATUS','status'],'')).toUpperCase(),tpl=String(find(x,['MODELO_ID','templateId','ASSUNTO','subject'],'')).toUpperCase();if(d&&start(d).getTime()===today.getTime()&&/ENVIADO|SENT|SUCESSO/.test(st))sent++;if(/PENDENTE|QUEUE|FILA/.test(st))pending++;if(/ERRO|FALHA|FAILED/.test(st))errors++;if(/PORTAL|CONVITE/.test(tpl)&&/ENVIADO|SENT|SUCESSO/.test(st))invites++});if(automation&&automation.sentToday!=null)sent=Number(automation.sentToday)||0;if(automation&&automation.queue){pending=Number(automation.queue.pending)||pending;errors=Number(automation.queue.error)||errors}set('atlas-kpi-communications',sent);set('atlas-comm-today',sent);set('atlas-comm-pending',pending);set('atlas-comm-errors',errors);set('atlas-portal-invited',invites);var clients=+((el('atlas-kpi-clients')||{}).textContent||0),p=Math.max(0,clients-invites),rate=clients?Math.min(100,Math.round(invites/clients*100)):0;set('atlas-portal-pending',p);set('atlas-portal-rate',rate+'%');var bar=el('atlas-portal-progress');if(bar)bar.style.width=rate+'%'}
function mark(id,ok){var n=el(id);if(n)n.className=ok?'ok':'error'}
function render(data,source){data=data||{};var summary=data.summary||{},auto=data.automation||{},health=data.health||{};set('atlas-kpi-clients',summary.activeClients||((data.clients||[]).filter(function(x){return x.active!==false}).length)||0);renderCertificates(data.certificates||[]);renderTimeline(data.timeline||[]);renderAgenda(data.agenda||[]);renderComms(data.communications||[],auto);set('atlas-gmail-quota',find(auto,['remainingQuota','gmailQuota','quota'],'—'));mark('health-api',health.api!==false);mark('health-data',health.dataFoundation!==false);mark('health-gmail',health.gmail!==false);mark('health-triggers',Boolean(health.triggers));var ok=health.api!==false&&health.dataFoundation!==false,status=el('atlas-health-summary');if(status){status.textContent=ok?'Operacional':'Atenção';status.className='cockpit-health-pill '+(ok?'ok':'error')}set('atlas-comm-status',health.triggers?'Automação ativa e pronta para processar a fila.':'Automação disponível; verificando gatilhos em segundo plano.');var stamp=data.meta&&data.meta.generatedAt?date(data.meta.generatedAt):new Date();set('atlas-last-refresh',(source==='cache'?'instantâneo • ':'')+new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit'}).format(stamp||new Date()))}
function readCache(){var c=window.AtlasSharedCache&&window.AtlasSharedCache.read(CACHE);return c&&c.data}
function writeCache(data){if(window.AtlasSharedCache)window.AtlasSharedCache.write(CACHE,data)}
async function loadCore(force){if(!window.AtlasAPI||!window.AtlasAPI.isConfigured())throw new Error('Atlas API não configurada.');var data=await window.AtlasAPI.cockpit({forceRefresh:Boolean(force),mode:'core'}),old=readCache()||{};data.automation=old.automation||data.automation;data.health=Object.assign({},old.health||{},data.health||{});render(data,'network');writeCache(data);return data}
async function loadSecondary(){if(!window.AtlasAPI)return;var base=readCache()||{};var jobs=[window.AtlasAPI.listCommunications({limit:200}).catch(function(){return base.communications||[]}),window.AtlasAPI.automationStatus().catch(function(){return base.automation||null})];var out=await Promise.all(jobs);base.communications=out[0]||[];base.automation=out[1]||null;base.health=Object.assign({},base.health||{},{gmail:!!base.automation,triggers:!!(base.automation&&base.automation.triggers&&base.automation.triggers.length)});base.meta=Object.assign({},base.meta||{},{generatedAt:new Date().toISOString()});render(base,'network');writeCache(base)}
function init(){activateCards();var session=window.AtlasAuth&&window.AtlasAuth.session?window.AtlasAuth.session.getActive():null;if(session)document.querySelectorAll('[data-auth-user-first-name]').forEach(function(n){n.textContent=String(session.user.displayName||'Usuário').split(' ')[0]});var h=new Date().getHours();set('atlas-greeting',h<12?'Bom dia':h<18?'Boa tarde':'Boa noite');var cached=readCache();if(cached)render(cached,'cache');var b=el('atlas-refresh');if(b)b.onclick=function(){b.disabled=true;loadCore(true).then(loadSecondary).catch(showError).finally(function(){b.disabled=false})};loadCore(false).then(function(){setTimeout(loadSecondary,0)}).catch(showError)}
function showError(e){console.warn('Atlas Cockpit:',e);var s=el('atlas-health-summary');if(s&&!readCache()){s.textContent='Atenção';s.className='cockpit-health-pill error'}set('atlas-last-refresh',readCache()?'dados instantâneos • atualização pendente':'falha ao atualizar')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})(window,document);
