(function(w,d){
'use strict';
var $=function(id){return d.getElementById(id)};
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function parseDate(v){if(!v)return null;var s=String(v).trim(),m;if((m=s.match(/^(\d{2})\/(\d{2})\/(\d{4})/)))return new Date(+m[3],+m[2]-1,+m[1]);var x=new Date(s);return isNaN(x)?null:x}
function days(v){var x=parseDate(v);if(!x)return null;var a=new Date();a.setHours(0,0,0,0);x.setHours(0,0,0,0);return Math.round((x-a)/86400000)}
function certDate(c){return c.DATA_VENCIMENTO||c.VALIDADE||c.VENCIMENTO||c.dataVencimento||c.validade}
function clientId(c){return c.CLIENTE_ID||c.ID_CLIENTE||c.clienteId||c.id}
function score(data){var c=data.cliente||{},certs=data.certificados||[],comms=data.comunicacoes||[],s=55,reasons=[],next='Revisar cadastro';
 if(c.email){s+=10}else{reasons.push('E-mail não cadastrado');s-=12}
 if(c.telefone||c.whatsapp){s+=7}else{reasons.push('Telefone não cadastrado');s-=8}
 var ds=certs.map(function(x){return days(certDate(x))}).filter(function(x){return x!==null}).sort(function(a,b){return a-b});var nearest=ds.length?ds[0]:null;
 if(nearest!==null){if(nearest<0){s-=25;reasons.push('Certificado vencido');next='Contatar para renovação imediata'}else if(nearest<=7){s-=10;reasons.push('Vencimento em '+nearest+' dia(s)');next='Enviar aviso de 7 dias'}else if(nearest<=30){s+=2;reasons.push('Vencimento próximo');next='Enviar comunicação de renovação'}else{s+=8;next='Acompanhar relacionamento'}}else{reasons.push('Sem validade identificada');s-=5}
 if(comms.length){s+=Math.min(10,comms.length*2)}else{reasons.push('Nenhuma comunicação registrada');s-=6}
 s=Math.max(0,Math.min(100,Math.round(s)));var level=s>=80?'Cliente fidelizado':s>=65?'Renovação provável':s>=45?'Necessita atenção':'Risco elevado';return {score:s,level:level,reasons:reasons,next:next,nearest:nearest}}
function renderAI(data){var p=$('crm-panel-inteligencia');if(!p)return;var r=score(data),c=data.cliente||{},cls=r.score>=80?'good':r.score>=60?'ok':r.score>=40?'warn':'danger';p.innerHTML='<div class="aie-card"><div class="aie-score '+cls+'"><small>Score Atlas</small><strong>'+r.score+'</strong><span>'+esc(r.level)+'</span></div><div class="aie-analysis"><span class="agr-eyebrow">Atlas IA • Copiloto operacional</span><h3>'+esc(c.nome||'Cliente')+'</h3><p>Leitura automática do cadastro, certificados e comunicações disponíveis.</p><ul>'+r.reasons.map(function(x){return '<li>'+esc(x)+'</li>'}).join('')+'</ul><div class="aie-next"><small>Próxima ação recomendada</small><strong>'+esc(r.next)+'</strong></div><div class="aie-actions"><a class="button" href="comunicacao.html?cliente='+encodeURIComponent(clientId(c)||'')+'&sugestao='+encodeURIComponent(r.next)+'">Gerar comunicação</a><button type="button" id="aie-audit-action">Registrar recomendação</button></div></div></div>';
 var b=$('aie-audit-action');if(b)b.onclick=function(){try{w.AtlasAPI.audit('AIE_RECOMMENDATION_VIEWED',{clientId:clientId(c),score:r.score,recommendation:r.next});b.textContent='Recomendação registrada'}catch(e){b.textContent='Registro indisponível'}}}
function addTab(){var nav=$('crm-drawer-tabs');if(!nav||$('aie-tab'))return;var b=d.createElement('button');b.id='aie-tab';b.type='button';b.dataset.tab='inteligencia';b.textContent='Atlas IA';nav.appendChild(b);var body=nav.nextElementSibling,p=d.createElement('section');p.className='crm-tab-panel';p.dataset.panel='inteligencia';p.id='crm-panel-inteligencia';body.appendChild(p)}
function renderNotifications(items){var list=$('aie-notification-list'),count=$('aie-notification-count');if(!list)return;count.textContent=items.length;count.hidden=!items.length;list.innerHTML=items.length?items.map(function(i){return '<a href="'+i.href+'"><span>'+i.icon+'</span><div><strong>'+esc(i.title)+'</strong><small>'+esc(i.text)+'</small></div></a>'}).join(''):'<p class="aie-empty">Nenhum alerta prioritário.</p>'}
async function loadNotifications(){try{var r=await Promise.all([w.AtlasAPI.listClients(),w.AtlasAPI.listCertificates()]),clients=r[0]||[],certs=r[1]||[],items=[],expired=0,d7=0,d30=0;certs.forEach(function(c){var n=days(certDate(c));if(n===null)return;if(n<0)expired++;else if(n<=7)d7++;else if(n<=30)d30++});var noMail=clients.filter(function(c){return !(c.EMAIL||c.email||c.EMAIL_PRINCIPAL)}).length;if(expired)items.push({icon:'!',title:expired+' certificado(s) vencido(s)',text:'Regularização necessária',href:'clientes.html?filter=expired'});if(d7)items.push({icon:'7',title:d7+' vencendo em até 7 dias',text:'Contato de alta prioridade',href:'clientes.html?filter=7'});if(d30)items.push({icon:'30',title:d30+' vencendo em até 30 dias',text:'Preparar renovação',href:'clientes.html?filter=30'});if(noMail)items.push({icon:'@',title:noMail+' cliente(s) sem e-mail',text:'Completar dados de contato',href:'clientes.html'});renderNotifications(items)}catch(e){renderNotifications([])}}
function init(){addTab();var btn=$('aie-notification-button'),panel=$('aie-notification-panel');if(btn&&panel){btn.onclick=function(){var open=panel.hidden;panel.hidden=!open;btn.setAttribute('aria-expanded',String(open));if(open)loadNotifications()};d.addEventListener('click',function(e){if(!panel.hidden&&!panel.contains(e.target)&&!btn.contains(e.target)){panel.hidden=true;btn.setAttribute('aria-expanded','false')}})}d.addEventListener('atlas:client-opened',async function(e){try{var data=await w.AtlasAPI.getClient(e.detail.clientId);renderAI(data)}catch(err){var p=$('crm-panel-inteligencia');if(p)p.innerHTML='<p>Não foi possível gerar a análise inteligente.</p>'}});loadNotifications();}
if(d.readyState==='loading')d.addEventListener('DOMContentLoaded',init);else init();
})(window,document);
